"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EndUserLayout from "../components/layouts/EndUserLayout";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const pageToHideLayout = pathname == "/admin";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <ReactQueryProvider>
            {pageToHideLayout ? (
              <>{children}</>
            ) : (
              <div>
                <EndUserLayout>{children}</EndUserLayout>
              </div>
            )}
          </ReactQueryProvider>
        </Provider>
      </body>
    </html>
  );
}
